### ISSUE TITLE
traefik (or another reverse proxy) configuration

### ISSUE THREAD

**Issue by progressify** [cshum/imagor#1]
hi

there is a way to configure imagor under traefik or another reverse proxy?
thank you

**Comment by cshum** [comment]
If you are using Kubernetes, you may do so by setting up a `Deployment` for the docker image `shumc/imagor:0.2.0`.
By default, Imagor listens to port 8000. You can override the port number by specifying `PORT` environment variable.

Create a `Service` that exposes the http service from `targetPort` 8000 to `port` 80.

Then create the `Ingress` that forwards traffic to the said service at `servicePort` 80, which is the reverse proxy.
