### ISSUE TITLE
Access log

### ISSUE THREAD

**Issue by mrtmexx** [cshum/imagor#10]
Hi,

How can I enable the HTTP access log for the `imagor`? If it is possible how can I change the log format?

**Comment by cshum** [comment]
Docker image `shumc/imagor:0.2.11` added access log support by setting the environment variable `SERVER_ACCESS_LOG=1`.

The default log format is json, such that it can be ingested by logging stack like ELK or Cloudwatch out of box. 
You may also set `DEBUG=1` for a more verbose and human readable format.
