### ISSUE TITLE
Clarification for different storage buckets

### ISSUE THREAD

**Issue by nasmorn** [cshum/imagor#11]
I don't quite understand what the difference between `result-loader` and `result-storage` would be? Can this be the same bucket?
The same applies to `loader` and `storage`. Is this to guard against deletion in the `loader` bucket?

In my simple mind the server would load something and then serve a result (optionally storing it). Thus I don't see where exactly the other two buckets come into play.

Thank you for your great work

**Comment by cshum** [comment]
Basically `loader` and `storage` are the source and destination of the *original* image; `result loader` and `result storage` are the source and destination of the *processed* image.

The Imagor library accepts multiple loader and storages, and the configuration pipeline works this way:

File Result Loader -> S3 Result Loader -> File Loader -> S3 Loader ->  HTTP Loader 

-  Imagor first load from the file/s3 result loaders, so if image has already been processed it does not need to be re-processed.
-  It then load from the file/s3 loaders for original image source.
-  If all above not found, it fetches the image url directly using HTTP loader

The reason for separated config for `loader` and `storage` is to give flexibility. For example:
-  you want to load file from static directory but you don't want to modify it, then you can enable `file loader` without `file storage`
-  you want to store the resulting image but you always want to process it live, then you can enable `file storage` without `file loader`

Though in normal circumstances, yes you would normally want the `loader` and `storage` pair to be on the same bucket.

Thanks for raising it up. I do agree more documentations clarifying the `loader` and `storage`, `result loader` and `result storage` pipeline would do great benefit.

**Comment by nasmorn** [comment]
Thanks a lot for the detailed answer.
