### ISSUE TITLE
S3 paths with url encoding not working

### ISSUE THREAD

**Issue by r0bdiabl0** [cshum/imagor#12]
I am currently testing locally imagor as a drop in replacement for our Thumbor implementation. We currently use an S3 loader and we're trying to emulate that with our local testing. However, we are getting errors when trying to implement it. I believe it has to do with url encoding special characters in the file path.

Here is the url we are using:

```
http://localhost:8888/unsafe/400x200/smart/photos/j/006b8bbe2c1baa8f2d12c06988a6efa7a15f048d.jpg
```

Here is the result:

```
{"message":"Get \"https://photos/j/006b8bbe2c1baa8f2d12c06988a6efa7a15f048d.jpg\": dial tcp: lookup photos on 127.0.0.11:53: no such host","status":500}
```

If I url encode the path of the photo, then it works:

```
photos%2Fj%2F006b8bbe2c1baa8f2d12c06988a6efa7a15f048d.jpg
```

But if the url encoded path has special characters in the filename, such as `{` to `%7B`, it gets an error:

```
photos%2F{1089856636549d026d369fb}.jpg
```
to
```
photos%2F%7B1089856636549d026d369fb%7D.jpg
```

```
{"message":"Get \"https://photos/%7B1089856636549d026d369fb%7D.jpg\": dial tcp: lookup photos on 127.0.0.11:53: no such host","status":500}
```

I'm assuming this is an issue because when querying s3 for the file, imagor is passing the url-encoded string instead of the actual filename. imagor should probably url-decode the string before making the request to s3. Thoughts?

**Comment by cshum** [comment]
This path 
```
http://localhost:8888/params/unsafe/400x200/smart/photos/j/006b8bbe2c1baa8f2d12c06988a6efa7a15f048d.jpg
```
will look up image key at `photos/j/006b8bbe2c1baa8f2d12c06988a6efa7a15f048d.jpg` and 
this path 
```
http://localhost:8888/params/unsafe/400x200/smart/photos%2Fa%2F0007d617bc5be3e50ded00381764071dcec079cd.jpg
```
will look up image key at `photos/a/0007d617bc5be3e50ded00381764071dcec079cd.jpg`

is`/a/` supposed to be the correct one?

To further drill down into the issue, would you also share any environment variable or arguments related (except the AWS credentials)?

**Comment by r0bdiabl0** [comment]
Sorry, I was playing with 2 different image filename when I was writing the issue. I updated my comment to reflect the same filename for the first use case. That is not the issue however. It's when the file name has a special character in it such as `{` as shown further down in the comment.

I'm not using any special env variables or arguments, just the standard config as mentioned in your docs:

Fake Creds:
```
      - AWS_ACCESS_KEY_ID=34jkl5hl34jkh5l3jk45
      - AWS_SECRET_ACCESS_KEY=234jh2lk34j5l23jk4l243ljk5n23ljk
      - AWS_REGION=us-west-2
      
      - S3_LOADER_BUCKET=mybucket.photos # enable S3 loader by specifying bucket
```

**Comment by r0bdiabl0** [comment]
I did some research and found that Amazon keys only require certain characters to be escaped. In your code, when you are encoding the file name and path, you are encoding all special characters, which then creates a problem for filenames that are not encoded in s3 using characters such as curly brackets `{` and `}`.  Instead of using the default encoder provided by golang in your normalize function, you can use a special function just for Amazon S3.

I'm not sure how you would create this in golang but here is an example function using javascript:

```
function encode(filename) {
    const encodings = {
        '\+': "%2B",
        '\!': "%21",
        '\"': "%22",
        '\#': "%23",
        '\$': "%24",
        '\&': "%26",
        '\'': "%27",
        '\(': "%28",
        '\)': "%29",
        '\*': "%2A",
        '\,': "%2C",
        '\:': "%3A",
        '\;': "%3B",
        '\=': "%3D",
        '\?': "%3F",
        '\@': "%40",
    };

    return filename.replace(
        /([+!"#$&'()*+,:;=?@])/img,
        match => encodings[match]
    );
}
```

The encodings constant are the actual characters that need to be encoded in S3.

**Comment by r0bdiabl0** [comment]
I was able to find a golang example here:

```
func zip(a1, a2 []string) []string {
	r := make([]string, 2*len(a1))
	for i, e := range a1 {
		r[i*2] = e
		r[i*2+1] = a2[i]
	}
	return r
}

func s3encoder(str string) string {
	array1 := []string{
		"+",
		"!",
		"\"",
		"#",
		"$",
		"&",
		"'",
		"(",
		")",
		"*",
		",",
		":",
		";",
		"=",
		"?",
		"@",
	}
	array2 := []string{
		"%2B",
		"%21",
		"%22",
		"%23",
		"%24",
		"%26",
		"%27",
		"%28",
		"%29",
		"%2A",
		"%2C",
		"%3A",
		"%3B",
		"%3D",
		"%3F",
		"%40",
	}
	str = strings.NewReplacer(zip(array1, array2)...).Replace(str)
	return str
}
```
I created this in go playground to demonstrate: [https://go.dev/play/p/A-DuMRHvmTT](https://go.dev/play/p/A-DuMRHvmTT)

**Comment by cshum** [comment]
also the `{` `}` characters seems to be Characters to avoid?
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines-avoid-characters

**Comment by cshum** [comment]
I am creating a common function for customizing safe characters. Let me know if you feel any more characters are safe to be added to the whitelist?
https://github.com/cshum/imagor/pull/14/files#diff-2fbeeacc5445e50e9e5845920890e3827ce8a9191756d13932c4e5ccbccbdd83R64

**Comment by cshum** [comment]
Would you pleasetry out `shumc/imagor:0.6.2`, which added configurable safe characters. 
You may add the following environment variables to skip escaping curly braces:
```
S3_SAFE_CHARS={}
```

**Comment by r0bdiabl0** [comment]
Thanks! I like the idea of making it user configurable as well. Even though Amazon recommends avoiding those characters, os's like Windows and legacy websites didn't prevent anyone from naming filenames anything they wanted. We have hundreds of thousands old user uploaded photos from back to 2002 that were using curly braces in the filenames so it wouldn't be fun to try and fix that now.

I'll go ahead and test this out.

**Comment by r0bdiabl0** [comment]
I've tested this latest update with multiple scenarios and hundreds of different filenames and it appears to work great. I feel confident putting it into our production environment and will keep a close eye on it as well as compare performance.

**Comment by cshum** [comment]
Glad it is working out so far.
