### ISSUE TITLE
Proxy for idempotent behaviour

### ISSUE THREAD

**Issue by gedw99** [cshum/imagor#129]
With a proxy and TTL cache when we make the same request again it will use the cache.

is there anything like this currently in the code base ?

**Comment by cshum** [comment]
Normally you would have a CDN or reverse proxy in front to handle caching. But if you need all that with Imagor alone, you may enable [Result Storage](https://github.com/cshum/imagor#loader-storage-and-result-storage) with expiration options:
```
-file-result-storage-expiration duration
        File Result Storage expiration duration e.g. 24h. Default no expiration
-s3-result-storage-expiration duration
        S3 Result Storage expiration duration e.g. 24h. Default no expiration
-gcloud-result-storage-expiration duration
        Google Cloud Result Storage expiration duration e.g. 24h. Default no expiration
```
depending which `Result Storage` you have enabled.
