### ISSUE TITLE
Resizing Not Working If Increasing Image Size W/O Stretch Param

### ISSUE THREAD

**Issue by r0bdiabl0** [cshum/imagor#15]
As we are testing imagor as a true drop-in replacement for Thumbor, we have noticed that the basic resizing of an image does not work the same when trying to make an image larger.

For example, with Thumbor, if I want to make an image that is 640x480 increase to a width of 780, I can simply use these minimal URL parameters:

```
http://localhost:8000/unsafe/780x0/photos%2Fb%2Fef88c521cbbb57e05c12a2dcc696724f12c9155f.jpg
```

Using that same URL in imagor displays the image in it's original size.

I know that imagor does not have all of the features as Thumbor as of yet but wanted to point this out because it is a basic way to increase image sizes that I'm sure I'm not the only one doing this. Even though imagor offers a `stretch` param that works, to be a true drop in replacement, it would be nice to not have to use this as it may not be easy to change the url params in whatever backend code utilizes it.

**Comment by cshum** [comment]
Thanks for reporting! Please try `shumc/imagor:0.6.4`, which fixes upscale resizing with unspecified width/height.
