### ISSUE TITLE
Suggestion :: Encode the storage path

### ISSUE THREAD

**Issue by jvahldick** [cshum/imagor#153]
Hi there,

I'm currently dealing with the following issue from S3 Storage:
KeyTooLongError (https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html)

As I try to work with the images with multiple layers, the URL gets longer for every image I generate. Example of a processed image:
https://url.com/processed/filters%3Awatermark%28df4bb201-03d2-4cb7-bf1b-c68e1d787009/original.png%2C-75%2C-51%2C0%2C18%2C10%29/processed/filters%253Awatermark%2528https%253A/url.com/processed/413x111%25253A723x421/smart/4d262fd3-1f67-40ad-a0c7-c37a3910083d/original.jpeg%252C135%252C-165%252C0%252C17%252Cnone%2529/processed/filters%25253Awatermark%252528https%2525253A%2525252F%2525252Furl.com%2525252F1500x165%2525252Ffilters%2525253Afill%25252528FFFFFF%25252529%2525253Aformat%25252528png%25252529%2525252Fb7161cdf-3afd-42c1-9a57-7c5100f4a4b8%2525252Ftransparent-pixel.png%25252Ccenter%25252Cbottom%25252C0%252529/processed/filters%2525253Awatermark%25252528https%252525253A%252525252F%252525252Furl.com%252525252F270x785%252525252Ffilters%252525253Afill%2525252528EAEAEA%2525252529%252525253Aformat%2525252528png%2525252529%252525252Fb7161cdf-3afd-42c1-9a57-7c5100f4a4b8%252525252Ftransparent-pixel.png%2525252Cleft%2525252Ctop%2525252C0%25252529/processed/1500x785/center/middle/8b881144-4c46-4c50-843f-488d2cc74baf/original.jpg

One suggestion to reduce the number of characters for that is to try to hash the path when storing it. What do you think about it? 
I believe this would help out to reduce the number of chars considerably. 

Thanks in advance.

**Comment by jvahldick** [comment]
Looking over the code, maybe an option can be added to allow us to choose hashed paths. When setting the statKey we can hash it with sha1 or so. I saw a similar request on this post:
https://github.com/cshum/imagor/issues/29#issuecomment-1098679645

**Comment by jvahldick** [comment]
Cool! That has been quick.

I spent a good chunk of my last two days trying to do it 😄 
https://github.com/jvahldick/imagor/commit/f10fe00c91f19c252c974767865080db2cab564e

Your looks way better

**Comment by cshum** [comment]
Yes the result storage follows `FILE_RESULT_STORAGE_BASE_DIR`. If you are meant to reuse result storage cache from storage (though I have never thought about such usage haha), you may set `FILE_STORAGE_BASE_DIR` and  `FILE_RESULT_STORAGE_BASE_DIR` to be the same directory.

**Comment by cshum** [comment]
Now available in `shumc/imagor:1.1.0`! 
Named path style: https://github.com/cshum/imagor#storage-and-result-storage-path-style

**Comment by jvahldick** [comment]
Thanks Adrian
