### ISSUE TITLE
watermark position

### ISSUE THREAD

**Issue by gingerlime** [cshum/imagor#18]
followup from #16 

`http://localhost:8000/unsafe/fit-in/1200x800/filters:fill(yellow):watermark(https://i.imgur.com/71LaQJU.png,-10,-10,0):format(jpeg)/upload.wikimedia.org/wikipedia/commons/a/a9/St_Francis_Seminary.jpg`

using thumbor:

![St_Francis_Seminary thumbor](https://user-images.githubusercontent.com/524274/151606502-d34437ee-0db4-4446-95d4-cd5af6b16706.jpg)

using imagor:

![St_Francis_Seminary imagor](https://user-images.githubusercontent.com/524274/151606526-de3a4f48-ed25-427a-8b24-ee96301537bc.jpg)

**Comment by cshum** [comment]
Hi @gingerlime it is a regression on v0.8.0. Fixed now on v0.8.1 `shumc/imagor:0.8.1` :)

**Comment by gingerlime** [comment]
Thank you @cshum ! It works perfectly now 👍
