### ISSUE TITLE
Compatibility with Google Cloud Storage

### ISSUE THREAD

**Issue by mplibunao** [cshum/imagor#19]
Hi, just found this library and it looks like a great alternative to imaginary.

Just wondering if I'm able to swap out S3 storage with Google Cloud Storage.

From the docs, I'm guessing it's not possible right now because you're putting just the bucket name

**Comment by cshum** [comment]
Google Cloud Storage uses SDKs different from S3, which is currently not implemented.

This would require implementing another storage adaptor, similar to the AWS S3 and file system ones that is currently available: https://github.com/cshum/imagor/tree/master/storage

If you are familiar with Go and Google Cloud Storage, feel free to create a pull request. I am happy to create a Cloud Storage adaptor at some point, though I have not used Google Cloud so I would need someone to test it out for me :P.
