### ISSUE TITLE
compression?

### ISSUE THREAD

**Issue by gingerlime** [cshum/imagor#20]
Hey @cshum it's me again :)

This is more of a request/wish than anything, but I'd be curious if it's possible to push the limits a bit... I wonder if the quality filter or some other potential compression filter can be applied to make images smaller?

For example, I took the gopher image from the examples using

`http://localhost:8000/unsafe/filters:hue(290):saturation(100):fill(yellow):format(jpeg):quality(80)/raw.githubusercontent.com/cshum/imagor/master/testdata/gopher.png`

and I get this image (136kb)

![gopher](https://user-images.githubusercontent.com/524274/151833075-6fcb7b38-d0ca-4100-afe9-ed8e01fc2389.jpg)

If I then compress it with tinypng.com it compresses it to 104kb ... not sure if it's lossy or lossless though

![gopher tinypng](https://user-images.githubusercontent.com/524274/151833265-ab06c1c5-80a0-4083-a6f2-236f429ed4c9.jpg)

I played around with some of our images, and the difference in size can be even bigger...

Is it purely a question of fine-tuning the quality? or is there some other compression that can be used?

**Comment by gingerlime** [comment]
The original png is 111kb btw, and tinypng can compress it to 45k

**Comment by cshum** [comment]
I believe there are several parameters in libvips function, that allows trade off between compression time and compression quality. Which I assume it makes smaller image size but takes slight more time to generate.
https://www.libvips.org/API/current/VipsForeignSave.html#vips-jpegsave

Will try to test out each of those parameters, compare their image size vs. execution times.

**Comment by gingerlime** [comment]
Thank you @cshum

**Comment by cshum** [comment]
The parameter with maximum compression relies on `mozjpeg` being installed. 
https://www.libvips.org/API/current/VipsForeignSave.html#vips-jpegsave
```
For maximum compression with mozjpeg, a useful set of options is strip, optimize-coding, interlace, optimize-scans, trellis-quant, quant_table=3.
```
Using the mozjpeg options where mozjpeg is installed, it does produces the similar result 106kb at quality=80

![gopher (23)](https://user-images.githubusercontent.com/293790/152573402-62c7ee05-ea89-4543-8c72-68bbef3c65bf.jpeg)

However it seems to be indeed a tradeoff between compression quality and execution time, where mozjpeg can be comparably  slower. https://libjpeg-turbo.org/About/Mozjpeg

Furthermore it also requires additional dependencies to be installed in Dockerfile, or maybe even require different docker images for different jpeg encoder if one conflicts with another...

**Comment by gingerlime** [comment]
Thanks @cshum. I'm not sure what's the best strategy here, although from anecdotal experience, tinypng is doing a pretty good job with most images. I think it's based off of pngquant but I'm not sure... There's always a trade-off between compression and performance, but in many cases, especially for websites, smaller images are better, and caching can be very effective at making it worth paying the performance price?

How "pluggable" is imagor at the moment for those kinds of things? alternatively, how much do you think it should provide "out-of-the-box"? I know it's a big ask and definitely not something trivial to implement. However, if imagor had a similar compression as tinypng for most images, it would be a huge win.

Perhaps @jcupitt can suggest something here? :)

**Comment by jcupitt** [comment]
For the PNG version, you can get a similar result like this:

```
vips copy gopher.jpg gopher.png[palette,bitdepth=4,compression=9,dither=0]
```

To make:

![gopher](https://user-images.githubusercontent.com/580843/152638998-c953a4f1-1b04-4edc-ada4-386c4613eb17.png)

Which is 54kb. These settings depend on the image though -- this pic only has a a few colours, so 4 bits per pixel is plenty, and large, flat areas, so there's no need to dither.

Image optimisers like gifsicle and pngcrush work by exploring the set of options for each file format, tweaking each one and trying to home in on the best combination of parameters that don't disrupt the image too badly. This can produce great results, but can also be horribly slow, since you have to experimentally recompress the image many, many times.

I think file size optimisation is out of scope for libvips. I suppose you could write an optimiser on top of libvips -- but I don't intend to do it!

**Comment by jcupitt** [comment]
Oh, one more thing (sorry) libvips has a plugin system, so you could replace (for example) the jpeg compressor at runtime if you wanted. It wouldn't be much work to make a moz save plugin.

As @cshum says, mozjpeg is a lot slower than libjpeg-turbo, so if you are aiming to keep latency low, it's not a good idea.

Anyway, the classic engineering problem: what are you aiming to optimize? Latency, bandwidth, or CPU load?

**Comment by gingerlime** [comment]
Thanks @jcupitt. Yes, definitely tricky. perhaps it's out of scope for imagor, although I think it would be really nice to have some compression filters available or some way to plug in something into some kind of pipeline ... very hand wavy, I know, I'm not really sure how to glue this together.

FWIW, the thumbor optimizers offered some compression options as far as I recall, but they would need to all be included in the docker container and the setup wasn't super straightforward.

**Comment by cshum** [comment]
`shumc/imagor:0.8.16` added support for auto WebP conversion, which outputs WebP automatically if browsers support webp (detect via `Accept` header) and `format()` filter is not specified.
```
IMAGOR_AUTO_WEBP=1
```
This can also be an option if image size is a concern. WebP compresses mostly better than MozJPEG, works with transparent image as well as animated images. It is supported by all major browsers nowadays.

**Comment by gingerlime** [comment]
Thank you @cshum ! it looks great.

**Comment by skurfuerst** [comment]
Hey @cshum ,

thanks for this awesome project :)

For my project, File sizes are also extremely important. I played with https://squoosh.app/ which can reduce file size by an additional 30-50% compared to what Imagor / Libvips does (on the expense of latency).

Would you be open for adding a feature which shinks a binary image through some external toolchain? I am thinking about the following idea:

- have a background worker queue which optimizes image file sizes.
- for the first request, run Imagor as usual and deliver the image.
- before storing the image in the cache, add it to the background worker queue.
- the background worker queue will then call external API / CLI / ... for compression (like sqoosh).


=> so after a while, the compressed image is delivered from the cache.

Would you be up for accepting  a pull request going into this direction? :-) I did not start working on this yet, as I first wanted to discuss it :) 

All the best,
Sebastian
