### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by cocorossello** [cshum/imagor#202]
Currently, there is no support for SVG. Even metadata request fails to detect svg:

`http://<imagor-url>/unsafe/meta/https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg`

returns:
`{"format":"jpeg","content_type":"image/jpeg","width":272,"height":92,"orientation":0,"pages":1,"exif":{}}`

Some filters or resizes don't make sense with svg, but can a basic and limited SVG support be considered?

**Comment by cshum** [comment]
It currently returns the an valid image if format is specified jpg, png, webp etc.

`http://<imagor-url>/unsafe/filters:format(webp)/https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg` 

But yes, by default it simply messed up and that's definitely a bug.

Returning SVG would be cool, but apart from filters and resize incompatibility, security is also a concern. It's so easy to embed malicious script in SVG and sanitizing it (without breaking it) is a pretty complex.

**Comment by cshum** [comment]
quick bump to v1.17 to fix the obvious issues
