### ISSUE TITLE
Security around image bombs

### ISSUE THREAD

**Issue by gnat** [cshum/imagor#22]
Thank you for your amazing work on this project! Was wondering if there's anything addressing or designing around mallicious images? Imgproxy mentions it here: https://github.com/imgproxy/imgproxy#security

 ```imgproxy checks the image type and its “real” dimensions when downloading. The image will not be fully downloaded if it has an unknown format or if the dimensions are too big (you can set the max allowed dimensions). This is how imgproxy protects from so called "image bombs”```

Thank you

**Comment by cshum** [comment]
Thanks for raising it. Imagor currently does not have specific logic around "image bomb protection". I am happy to look into this further.

Meanwhile a rule of thumb is to enable URL Signature https://github.com/cshum/imagor#url-signature. This works by generating a hash from the path and the server secret string. Only the path (image source included) that matches the signature shall be processed. This would dismiss any unconsented images being loaded without the correct signature generated from sever side.

If URL signature is NOT enabled - a lot of other bad things can happen, even with "image bomb protection" in place.

**Comment by WatchDogsDev** [comment]
> Thanks for raising it. Imagor currently does not have specific logic around "image bomb protection". I am happy to look into this further.
> 
> Meanwhile a rule of thumb is to enable [URL Signature](https://github.com/cshum/imagor#url-signature). This works by generating a hash from the path and the server secret string. Only the path (image source included) that matches the signature shall be processed. This would dismiss any unconsented images being loaded without the correct signature generated from sever side.
> 
> If URL signature is NOT enabled - a lot of bad things can happen, even with "image bomb protection" in place.

I think it can be a problem even when you are using signature. 
On backends with user upload capability, they can upload bomb images.

**Comment by cshum** [comment]
Imagor `0.9.12` now checks the image type and its resolution before the actual processing happens. The image processing will be rejected if the dimensions are too big (you can set the max allowed image resolution using -vips-max-resolution), which protects from so called "image bombs”.

**Comment by gnat** [comment]
Nice one! @cshum

**Comment by bhaskarmishra** [comment]
> Thanks for raising it. Imagor currently does not have specific logic around "image bomb protection". I am happy to look into this further.
> 
> Meanwhile a rule of thumb is to enable [URL Signature](https://github.com/cshum/imagor#url-signature). This works by generating a hash from the path and the server secret string. Only the path (image source included) that matches the signature shall be processed. This would dismiss any unconsented images being loaded without the correct signature generated from sever side.
> 
> If URL signature is NOT enabled - a lot of bad things can happen, even with "image bomb protection" in place.

How is putting the secret on client UI to sign secure?, Please correct me @cshum if I misunderstood it.

**Comment by cshum** [comment]
@bhaskarmishra no way you would put the secret on client side. 
The secret is stored server-side and you generate a hash using the stored secret in server side.
The generated hash is shared client-side but there is no way you can deduce the secret from the generated hash itself.
