### ISSUE TITLE
Support for path style S3 URL

### ISSUE THREAD

**Issue by mhhakim** [cshum/imagor#23]
Hi,
I am trying to use a S3 object storage which doesn't support subdomain style URL like **bucket.namespace.domain.tld**. It supports only path style URL like **namespace.domain.tld/bucket**. Can you please make changes to the s3storage adapter so that it could support path style URL too?
Maybe a new config option for s3 storage. Sometjing like S3_URL=path (default url) would be nice. I am not familiar with GO. So, I can't make a PR.

Thanks

**Comment by cshum** [comment]
This request URL is made by the AWS SDK, and I would suggest sticking to the official SDK where possible. 
Is `S3ForcePathStyle` from the AWS SDK, something you would be looking for?
https://github.com/aws/aws-sdk-go/blob/main/aws/config.go#L118
We can expose that config under Imagor instead.

**Comment by cshum** [comment]
@mhhakim would you please test this docker image tag `shumc/imagor:s3-force-path-style`

https://hub.docker.com/layers/shumc/imagor/s3-force-path-style/images/sha256-a1d2350264518647cb46f7cc51863f25331849abaa552e6c6d50313e2435814d?context=repo### 

with the additional environment variable 
```
S3_FORCE_PATH_STYLE=1
```

**Comment by mhhakim** [comment]
Working as intended! Thanks 🙏

**Comment by cshum** [comment]
Cool! The changes are now included in release `shumc/imagor:0.8.8`
