### ISSUE TITLE
Add feature to protect against SSRF in HTTP loader

### ISSUE THREAD

**Issue by thomasf** [cshum/imagor#239]
Maybe the current allow list and signed URLs are is enough but it would be nice to be able to totally block reject some networks for extra ease of mind.

I'm not sure about the settings granularity but a few settings would maybe be good to have, one list of manually specified CIDRs and some easier to configure boolean setting(s) to block private and loopback networks.

I believe this would require overriding the default Transport/Dialer/Resolver for the HTTP loader client so that requests can be aborted when a name resolves to an internal name. 

**edit**: found this article that describes the problem and has one solution https://goteleport.com/blog/ssrf-attacks/

**Comment by thomasf** [comment]
It looks like the Allowed Sources setting won't work with HTTP redirects because http.Client.CheckRedirect isn't implemented.

**Comment by cshum** [comment]
Interesting findings. Will take a closer look when I get some time. 

Do feel free to create a PR if you have any implementation plans.

**Comment by thomasf** [comment]
I might have time next week to take a look at the main SSRF issue.

**Comment by thomasf** [comment]
I am thinking using something like this.. 

It would add 4 new flags to the HTTP loader though.  I would assume that most of the times where anyone wants to block loopback networks they probably also want to block link local so those two options could probably be a single flag.

```go
type SafeDialer struct {
	UnsafeBlocks   []*net.IPNet
	BlockLoopback  bool
	BlockPrivate   bool
	BlockLinkLocal bool
}

func (s *SafeDialer) dialControl(network string, address string, conn syscall.RawConn) error {
	host, _, err := net.SplitHostPort(address)
	if err != nil {
		return err
	}
	addr := net.ParseIP(host)

	if s.BlockLoopback && addr.IsLoopback() {
		return fmt.Errorf("unauthorized request")
	}
	if s.BlockLinkLocal && (addr.IsLinkLocalUnicast() || addr.IsLinkLocalMulticast()) {
		return fmt.Errorf("unauthorized request")
	}
	if s.BlockPrivate && addr.IsPrivate() {
		return fmt.Errorf("unauthorized request")
	}

	for _, block := range s.UnsafeBlocks {
		if block.Contains(addr) {
			return fmt.Errorf("unauthorized request")
		}
	}
	return nil
}


```
