### ISSUE TITLE
focal filter not working with resizing

### ISSUE THREAD

**Issue by ipmb** [cshum/imagor#248]
Maybe I'm not understanding how the `focal` filter works. My expectation is that I can define a focal point in the image and imagor will try to crop/resize around it. When I generate an image with different focal points, I get the same results.

Using `docker run -p 8000:8000 -e VIPS_MAX_RESOLUTION=168000000 shumc/imagor -imagor-unsafe`

These produce the same image:

* `http://localhost:8000/unsafe/575x335/filters:focal(4000x7000)/https://images.unsplash.com/photo-1663524789632-509f6250460c`
* `http://localhost:8000/unsafe/575x335/filters:focal(10x10)/https://images.unsplash.com/photo-1663524789632-509f6250460c`

I would expect them both to generate 575x335 images with the first focused on the lower right portion of the image and the second focused on the upper left portion. (the original is 4672x7008)

**Comment by cshum** [comment]
The focal filter currently only works when `/smart/` applied:

First you find the crop region:
```
http://localhost:8000/unsafe/3000x5000:4000x6000/https://images.unsplash.com/photo-1663524789632-509f6250460c
```
which looks something like this:
![photo-1663524789632-509f6250460c (1)](https://user-images.githubusercontent.com/293790/202338858-15630b8b-128b-41c9-98b8-70a29b93b62d.jpeg)

Apply that focal region to smart cropping:
```
http://localhost:8000/unsafe/575x335/smart/filters:focal(3000x5000:4000x6000)/https://images.unsplash.com/photo-1663524789632-509f6250460c
```
![photo-1663524789632-509f6250460c (2)](https://user-images.githubusercontent.com/293790/202339196-ca70a3af-3000-4e05-a383-b36052684151.jpeg)

**Comment by ipmb** [comment]
Got it... thanks for the quick reply.

I was hoping to be able to just specify a single focal point, but it seems to have the desired effect if I define a very small rectangle (`focal(9x9:10x10)`).
