### ISSUE TITLE
Any advice on using imagor with lambda

### ISSUE THREAD

**Issue by oskarpearson** [cshum/imagor#25]
Hi @cshum

Would you be open to accepting PRs that add lambda support?

Have you perhaps done any experimentation with imagor in a AWS lambda environment? ​It'd probably involve integrating https://github.com/aws/aws-lambda-go support. https://aws.amazon.com/solutions/implementations/serverless-image-handler/ / https://github.com/aws-solutions/serverless-image-handler also uses libvips, so it should be reasonably possible to do so. That tool, however, doesn't support smart resizing without additional AWS services.

Additionally:

One of our use cases is that we serve images at common breakpoints. We've found that pre-caching images at the breakpoints improves end-user performance. Given this, I was wondering if you'd be open to accepting PRs that also change the operating model a bit? In short: I'd like a lambda that accepts an SQS request in Thumbor parameter format, fetches the origin image, resizes it, and then stores the result in an S3 result cache. This way, when a web browser makes a request for the same file with the same breakpoint it is already pre-built and can be returned by the http version of imagor. Or, if it's a miss, it'll perform the resize.

Thanks!

Oskar

**Comment by cshum** [comment]
Hi @oskarpearson thanks for your suggestions! I am more than happy to accept a PR :)

We did look around the https://github.com/aws-solutions/serverless-image-handler project. They expose lambda function as a web service through AWS API gateway.

Exposing lambda as a ALB target is cheaper, but their [1MB limit](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html) is not very practical for an image service like this. Exposing lambda through API gateway has a slightly better limit at 6MB, but imho the AWS API gateway is simply horrible to work with. Not to mention the total cost can be even higher than say, deploying under ECS. Which beats the whole purpose of using lambda.

However using lambda as an event receiver e.g. SQS, it does make a lot of sense. 

Once you are able to get libvips working inside the lambda environment, the Go part should be fairly straightforward. It would be something like a new entrypoint similar to https://github.com/cshum/imagor/blob/master/cmd/imagor/main.go, but wraps the lambda handler proxy https://github.com/awslabs/aws-lambda-go-api-proxy

**Comment by oskarpearson** [comment]
Thanks for the guidance and suggestions - really useful feedback @cshum and @gnat!

In our case we wouldn't post the image to lambda, so we wouldn't hit the API size limits. Instead we have the original file sitting in an S3 source bucket.

We're also likely to use the 'docker image' version of lambda, so there's less messing around with dependencies and similar. 

I'll have a look into the options here and hopefully submit a PR. It'll be my first real golang work, so please don't hesitate to critique it!

Thanks!
