### ISSUE TITLE
Different aws bucket for watermark and interpolator support

### ISSUE THREAD

**Issue by geevarghesest** [cshum/imagor#256]
Hello, I want to use a watermark image that is located in a different private AWS bucket. Is it feasible.
Also, is there an option to specify an interpolator to use while downsizing

**Comment by cshum** [comment]
You can specify different credentials for both S3 Loader and S3 Storage.  You may configure S3 Storage for normal images, then a different S3 Loader with the private AWS bucket.

**Comment by geevarghesest** [comment]
That worked!. Thanks for the tip

> You can specify different credentials for both S3 Loader and S3 Storage. You may configure S3 Storage for normal images, then a different S3 Loader with the private AWS bucket.
> 
> https://github.com/cshum/imagor#different-aws-credentials-for-s3-loader-storage-and-result-storage
