### ISSUE TITLE
Crop params in percent size

### ISSUE THREAD

**Issue by pletessier** [cshum/imagor#26]
Hi,
Thanks for this tool. It looks amazing !

My use case is to crop images by giving left-top and right-bottom coords as percent of width and height of the image.
So the params would be float values between 0 and 1, such as "0.10x0.08:0.26x0.43". 

Of course, I don't have image width and height infos on the client side, otherwise it would have been easy to compute pixels-coords automatically.

Is there any way to achieve this with the current version of Imagor ? If not, would you be open to a PR ?

**Comment by cshum** [comment]
Imagor currently does not support crop by percentage. PR is welcomed :)

**Comment by cshum** [comment]
Crop params in percentage is now available in docker image `shumc/imagor:0.8.11`!
