### ISSUE TITLE
Any way to set max height weight instead of set to a fixed height weight

### ISSUE THREAD

**Issue by askfor** [cshum/imagor#287]
Hi, Is there any way to set max height weight instead of set to a fixed height weight?
If the the origin image height weight is smaller than the max height weight, then just return it. if the origin image height weight is larger than the max height weight, then resize it to the max height weight.

**Comment by cshum** [comment]
Hi the option is `fit-in`:
```
http://localhost:8000/unsafe/fit-in/1000x1000/https://raw.githubusercontent.com/cshum/imagor/master/testdata/dancing-banana.gif
http://localhost:8000/unsafe/fit-in/1000x100/https://raw.githubusercontent.com/cshum/imagor/master/testdata/dancing-banana.gif
```

**Comment by askfor** [comment]
Thanks, fit-in does work, but I got another question, Is there any way to only set a max height or weight instead of set both values, the other one will be calculated from the orgin ratio automatically,

**Comment by askfor** [comment]
Hi thanks, `fit-in` does work, The problem I encountered was I also added the "fill(withe)" filter, I think this filter will make fit-in option don't work any more.
Doesn't the fill filter should be applied after the image was resized?

**Comment by cshum** [comment]
You can use `background_color(white)` instead:

```
http://localhost:8000/unsafe/fit-in/1000x1000/filters:background_color(cyan)/https://raw.githubusercontent.com/cshum/imagor/master/testdata/dancing-banana.gif
```

**Comment by askfor** [comment]
Got it, thank you.
