### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by s01cy** [cshum/imagor#298]
Hi, first of all - thanks for this awesome library :) 

I have a problem while trying to resize this [image](https://cdn.action.pl/File.aspx?CID=56405&UID=uab3010&PID=e588f4e679ab971d07534179af04ee6e&P=/Icecat/R6D1z8j4203051w6D4f212X282n6B6e8.jpg)

Full resize URL: 
`http://imagor:8000/unsafe/fit-in/360x360/filters:fill(white)/https://cdn.action.pl/File.aspx?CID=56405&UID=uab3010&PID=e588f4e679ab971d07534179af04ee6e&P=/Icecat/R6D1z8j4203051w6D4f212X282n6B6e8.jpg`

I get a 400 "Bad Request" response, tried both `IMAGOR_RETRY_QUERY_UNESCAPE=1`and `DEBUG=1` but params didn't help to debug this

Docker-compose env params:
```
      PORT: 8000
      IMAGOR_UNSAFE: 1
      IMAGOR_RETRY_QUERY_UNESCAPE: 1
      DEBUG: 1
```
How can I debug/resolve this issue? Thanks!

**Comment by cshum** [comment]
The image path contains `?&` characters and need to be escaped. What about 
```
http://imagor:8000/unsafe/fit-in/360x360/filters:fill(white)/https%3A%2F%2Fcdn.action.pl%2FFile.aspx%3FCID%3D56405%26UID%3Duab3010%26PID%3De588f4e679ab971d07534179af04ee6e%26P%3D%2FIcecat%2FR6D1z8j4203051w6D4f212X282n6B6e8.jpg
```
you can generate the escaped path with [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) or equivalent function:
```
encodeURIComponent('https://cdn.action.pl/File.aspx?CID=56405&UID=uab3010&PID=e588f4e679ab971d07534179af04ee6e&P=/Icecat/R6D1z8j4203051w6D4f212X282n6B6e8.jpg')
```

**Comment by s01cy** [comment]
Hi @cshum 
It worked, thanks for the help :)
