### ISSUE TITLE
s3 space in filename returns {"message":"invalid","status":400}

### ISSUE THREAD

**Issue by terkin** [cshum/imagor#306]
I am loading file `1 1.jpg` to s3 bucket, and trying to open it with imagor, but getting this error, I tried both `1%201.jpg` and `1+1.jpg` but it doesnt work, if there are any way to make it work for files with space in name or other special characters?

**Comment by cshum** [comment]
imagor follows s3 guidance https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines-safe-characters escaping all special characters except safe characters. 

If you wish to include space as s3 safe characters, you may do so with `S3_SAFE_CHARS`: 
```
S3_SAFE_CHARS=" "
```
