### ISSUE TITLE
default domain for original image url

### ISSUE THREAD

**Issue by AlekseyArh** [cshum/imagor#309]
Hi. 
There is a default scheme setting: **HTTP_LOADER_DEFAULT_SCHEME: "https"**

```
http://localhost:8000/unsafe/https://example.com/name.jpg
->
http://localhost:8000/unsafe/example.com/name.jpg
```

Is there anything similar for domain name?  **HTTP_LOADER_DEFAULT_DOMAIN: "example.com"**

```
http://localhost:8000/unsafe/example.com/name.jpg
->
http://localhost:8000/unsafe/name.jpg
```

**Comment by cshum** [comment]
I am not sure about default domain as it would be too ambiguous. e.g. Docker/Kubernetes service hostname 
```
http://minio/name.jpg
```
does not have a valid domain name but can be resolved properly. Populating a default domain
```
http://example.com/minio/name.jpg
```
would become invalid in this case

**Comment by AlekseyArh** [comment]
> I am not sure about default domain as it would be too ambiguous. e.g. Docker/Kubernetes service hostname
> 
> ```
> http://minio/name.jpg
> ```
> 
> does not have a valid domain name but can be resolved properly. Populating a default domain
> 
> ```
> http://example.com/minio/name.jpg
> ```
> 
> would become invalid in this case

I would like to hide the source of the image.

Something like this
h.DefaultDomain = if h.DefaultDomain not empty then h.DefaultDomain + "/"
`image = h.DefaultScheme + "://" + h.DefaultDomain + image`

I think if a person sets up a domain, then he will expect that an automatic domain assignment will occur.
Maybe I don't see the whole picture. Maybe there is another option to hide the source?

**Comment by cshum** [comment]
Even if default domain is expected, there is also a chance the path has a valid domain e.g.
```
https://example.com/aaa.org/name.jpg
```
This will also conflict with the automatic domain assignment

**Comment by cshum** [comment]
I suggest a base URL option, and it should cast the base URL no matter base valid domain or not: 
```
https://example.com/foo.org/bar/name.jpg <- source image
```
with base URL set to `https://example.com/foo.org`:
```
http://localhost:8000/unsafe/https://example.com/foo.org/bar/name.jpg
->
http://localhost:8000/unsafe/bar/name.jpg
```

**Comment by AlekseyArh** [comment]
> I suggest a base URL option, and it should cast the base URL no matter base valid domain or not:
> 
> ```
> https://example.com/foo.org/bar/name.jpg <- source image
> ```
> 
> with base URL set to `https://example.com/foo.org`:
> 
> ```
> http://localhost:8000/unsafe/https://example.com/foo.org/bar/name.jpg
> ->
> http://localhost:8000/unsafe/bar/name.jpg
> ```

Excellent =)

**Comment by cshum** [comment]
You may test the docker build at master branch:
https://github.com/cshum/imagor/pkgs/container/imagor/71301029?tag=master

```
ghcr.io/cshum/imagor@sha256:d9dfe9a06a0813cf655e10529a9e7ee8096e0c0a51c52b27d09e55d39c883bc9
```

available with `fill(transparent)` or `fill(none)`

**Comment by AlekseyArh** [comment]
> HTTP_LOADER_BASE_URL=https://raw.githubusercontent.com/cshum/imagor/master

Thank you, good man. it works!
