### ISSUE TITLE
confusing 404 warnings

### ISSUE THREAD

**Issue by ipmb** [cshum/imagor#31]
I just setup imagor and it's working great, but I see a lot of log lines like this

```json
{"level":"warn","caller":"imagor/imagor.go:305","ts":1646775438.21022,"key":"0x241:5017x3165/326x190/filters:strip_exif()/<escaped_http_url>","msg":"load","error":"imagor: 404 not found"}
```

Shortly after I see the 200 response in the access log

```json
{"status":200,"ts":1646775438.541976,"level":"info","ip":"xxx","caller":"server/handler.go:98","took":0.331850614,"uri":"/unsafe/0x241:5017x3165/326x190/filters:strip_exif()/<escaped_http_url>","msg":"access","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:37.0) Gecko/20100101 Firefox/37.0","method":"GET"}
```

I assume the 404 is coming from the result storage? I'm running with 

```
-file-result-storage-base-dir=/tmp -file-result-storage-expiration=1h
```

My intent with the result storage is to use it as a short-term cache, so misses are expected. Is there a way to silence this message?

Also, if my assumption is correct, using a "404 not found" message for a file not found on the filesystem was confusing and somewhat alarming for images I knew should be returning a 200. It would be nice to have a message that told me it didn't exist on the filesystem instead (maybe with the full path?).

**Comment by ipmb** [comment]
I ended up removing the file result storage. There was no noticeable difference in performance before/after, so I suspect that the cost of writing everything to disk was not significantly less work than regenerating a few thumbnails while our CDN is populated.

I'll leave this open, but it's not something I will need/use personally.

**Comment by cshum** [comment]
Hi @ipmb thanks for your feedback. I do agree the warn log from result storage is a bit of false alarm. May try to make that a debug log instead.

Meanwhile if you are serving images under a CDN, it may be easier to utilize CDN's cache rather than result storage. Unless you want to be able to retrieve the resulting images.

**Comment by cshum** [comment]
The 404 storage log now becomes debug level
