### ISSUE TITLE
Vary: Accept header when responding webp for cdn

### ISSUE THREAD

**Issue by AlekseyArh** [cshum/imagor#311]
`curl -I http://localhost:8000/...jpg -H 'Accept: image/webp'`
Content-Type: image/webp
Vary: Accept

`curl -I http://localhost:8000/...jpg`
content-type: image/jpeg

Can be solved via nginx
```
location / {
    if ($http_accept ~* webp) {
        add_header Vary Accept;
    }
    proxy_pass http://localhost:8000;
}
```
But I want to without nginx

**Comment by AlekseyArh** [comment]
I communicated with different CDNs. It turns out that the title should be given when the option "auto webp" is enabled

```
location / {
     add_header Vary Accept; // if auto webp is enabled on imagor
     proxy_pass http://localhost:8000;
}
```

**Comment by cshum** [comment]
You may test the docker build at master branch:
https://github.com/cshum/imagor/pkgs/container/imagor/70043557?tag=master

```
ghcr.io/cshum/imagor@sha256:aa43979a1bea938c1691469359c1b1b9e1869222085d1195914ce1acb3f30bd7
```

**Comment by AlekseyArh** [comment]
> You may test the docker build at master branch: https://github.com/cshum/imagor/pkgs/container/imagor/70043557?tag=master
> 
> ```
> ghcr.io/cshum/imagor@sha256:aa43979a1bea938c1691469359c1b1b9e1869222085d1195914ce1acb3f30bd7
> ```

Thanks! It works =)
