### ISSUE TITLE
Corrupt originals - yellow/green tint.

### ISSUE THREAD

**Issue by matthewrk** [cshum/imagor#339]
I am experiencing an intermittent problem where imagor appears to be corrupting the source image, saving that as an original and then failing to generate thumbnails from it.

Attached is an example of the source image, and a corrupted copy that imagor had cached as an original:

![source](https://user-images.githubusercontent.com/998908/224825719-94b75ffc-89c7-49d1-9bfd-34e78b770ffb.jpg)

![cached-original](https://user-images.githubusercontent.com/998908/224825750-6a364692-f8da-458a-a55d-fdbbbf14549d.jpg)

When attempting to use this original for a thumbnail, I get the following output:
` "error": "imagor: 406 VipsJpeg: Premature end of input file"`

I've seen this happen before and the corruption always looks the same, bottom 2/3rd yellow/green tint, some kind of broken frame from the left side etc.

Deleting the cache of the original and running it again seems to fix the issue.

Any ideas? I'm not sure where to look.

I'm using imagor 1.0.3 in a docker container.  Http loader. S3 storage.

**Comment by cshum** [comment]
Try the latest version?

**Comment by matthewrk** [comment]
Thanks for the suggestion - I hadn't realised the container image I was using had fallen so far behind. Was this a known issue that has been resolved in the newer versions? otherwise as it was intermittent it's going to take a while to verify that the problem is resolved, but hopefully that is the case.

**Comment by cshum** [comment]
Yes that was a known issue around 1.0.x related to streaming issues. Fixes were deployed around 1.2.x.

For old corrupted images, imagor cannot determine if it is a legit file caused an error, or indeed a corrupted image. So they are left untouched and need to be removed manually.

But for new images, imagor would try to clear its cache if the resulting image caused an error.

Lets reopen the issue if you reproduce any new findings.
