### ISSUE TITLE
Feature Request: minio(s3 protocol compatible) storage engine support.

### ISSUE THREAD

**Issue by leopku** [cshum/imagor#34]
First of all, thanks the author make this amazing project.  

Could you please add support for [minio](https://min.io/)?

**Comment by cshum** [comment]
Since minio is S3 compatible, I believe you can support minio using S3 Storage, by providing the custom `S3_ENDPOINT`?

**Comment by leopku** [comment]
Thanks a lot.
It works with custom S3_ENDPOINT
