### ISSUE TITLE
Image transformation is taking 2 sec for a single image transformation.

### ISSUE THREAD

**Issue by anvesh2609** [cshum/imagor#352]
We have deployed the imagor in the GKE cluster with storage as a GCS bucket. Any image transformation involving a resolution of above 2000x2000 takes around 2 sec to complete. Is this expected? Can I make this faster?

To be specific, I've added more time measurements for each step in the code and found that 

		buf, err := v.export(img, format, quality)

The above step alone takes 1.8 sec.

My Kubernetes pod specification:
CPU: 3 cores,
Memory: 2GB

we haven't changed any default parameters for concurrency or queue size. 

The URL we are using:
 
``` 
3134x3124/filters:hue(18):saturation(59):format(webp)/JDL/Hotel_Bill_for_Mumbai_Meeting.jpeg
```

Please let us know if 2s is expected or could I improve this speed?

**Comment by cshum** [comment]
Can you share a few example images?

**Comment by anvesh2609** [comment]
The attached image with the below transformations took "duration": "3.087542971s"

 <img width="1711" alt="ImagePushCDN" src="https://user-images.githubusercontent.com/13072967/230656143-92d17688-441f-4767-b0e3-d3bbdf2de997.png">

URL: 3000x3000/filters:format(jpg):fill(green):saturation(30)/Jio/ImagePushCDN_1680889804476.png

Kubernetes Pod specification:
    resources:
          limits(max):
            cpu: "3" cores
            memory: 10000Mi
          requests(min):
            cpu: "2"
            memory: 2000Mi

```
if !thumbnailNotSupported &&
		p.CropBottom == 0.0 && p.CropTop == 0.0 && p.CropLeft == 0.0 && p.CropRight == 0.0 {
```
The above if snippet took {"duration": "1.64588846s"}

```
buf, err := v.export(img, format, quality)
```

The above line took {"duration": "1.389943312s"}



---------------------------------------------------------------------------------------------------------

The same image for URL /2001x2000/filters:format(jpg):fill(green):saturation(30)/Jio/ImagePushCDN_1680889804476.png took {"duration": "1.544160271s"} for the same kube pod

```
if !thumbnailNotSupported &&
		p.CropBottom == 0.0 && p.CropTop == 0.0 && p.CropLeft == 0.0 && p.CropRight == 0.0 {
```
The above if snippet took {"duration": "824.234402ms"}

```
buf, err := v.export(img, format, quality)
```

The above line took {"duration": "637.551247ms"}

----------------------------------------------------------------------------------------------------------

For the URL /500x500/filters:format(jpg):fill(green):saturation(30)/Jio/ImagePushCDN_1680889804476.png, it took duration of {"duration": "702.544148ms"} with if block taking  {"duration": "559.537316ms"} and loading to buffer took {"duration": "52.842426ms"}.

----------------------------------------------------------------------------------------------------------

For the gopher image(), we saw below response times:
1. /500x500/filters:format(jpg):fill(green):saturation(30)/Jio/gopher.png   --- {"duration": "426.346406ms"}
2. /2000x2000/filters:format(jpg):fill(green):saturation(30)/Jio/gopher.png ----  {"duration": "1.303607538s"}
3. /3000x3000/filters:format(jpg):fill(green):saturation(30)/Jio/gopher.png ------ {"duration": "2.698786711s"}

![gopher](https://user-images.githubusercontent.com/13072967/230659361-78f86231-1a1a-4a3f-bc67-4f77c0cd96cb.png)
 

------------------------------------------------------------------------------------------------------------

It is the same pattern for any image we use with a similar pod configuration. 
Please suggest to us if we could change our pod config or imagor parameter to make this faster.
These will be all the transformations we will be doing. So, is there a way we could skip any of these steps?

**Comment by cshum** [comment]
fyi the `buf, err := v.export(img, format, quality)` will always takes the longest no matter which operations.
Because libvips performs lazy evaluations, which accumulated operations until it needs to be evaluated i.e. when the image is to be exported

**Comment by anvesh2609** [comment]
Understood! Thanks for clearing it up.

Anything I can change with the configuration? Also, what is the general benchmark response time for imagor for such high resolutions?

I'm worried that I'm not deploying and configuring the imagor to its optimum speed.

Thanks very much for all the help.

**Comment by cshum** [comment]
For a large resolution like 3000x3000 thats kinda expected though. But a general rule of thumb is libvips/imagor performs better weith jpeg/webp images and relatively slow with png.
