### ISSUE TITLE
Signed URl issue

### ISSUE THREAD

**Issue by bhaskarmishra** [cshum/imagor#357]
If the URL to be signed has query parameters in it 
like https://abc.com/images/a.png?p1=1&p2=3 
then imagor throws a signature mismatch. 

Looks like for signature matching it is only taking path whatever is before "?" into account.
If while signing I use just the path then signature matches but I get forbidden since it is trying to hit without params.

**Comment by cshum** [comment]
For image URI that contains ? character should be encoded with [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) or equivalent

**Comment by bhaskarmishra** [comment]
Thanks @cshum
