### ISSUE TITLE
http-loader does not forward http host header despite `-http-loader-forward-all-headers`

### ISSUE THREAD

**Issue by ThomasLohner** [cshum/imagor#36]
We want imagor to fetch images via internal network to make sure to avoid cdn optimizations and really load the **original** image. 

The upstream server has multiple vhosts configured to separate images for different domains:

```
10.1.1.1
vhost img.example.com -> /var/www/img.example.com/
vhost img.another.net -> /var/www/img.antoher.net/
```
We enabled `-http-loader-forward-all-headers` and tried requests like this:
```
curl -H "Host: img.another.net" -H "Foo: bar" http://<imagor_ip>/unsafe/fit-in/800x600/http://10.1.1.1/pic.jpg
```

This will produce the following request on the upstream server (which we tested with `netcat -ltp80`)
```
GET /pic.jpg HTTP/1.1
Host: 10.1.1.1
User-Agent: curl/7.58.0
Accept: */*
Foo: bar
```
As you can see the `Foo`-Header will be passed along due to `-http-loader-forward-all-headers` but the `Host`-Header is not.

This can be fixed with a `/etc/hosts` entry for each domain:
```
10.1.1.1 img.example.com
10.1.1.1 img.another.net
```
But i think it's at least misleading that `-http-loader-forward-all-headers` does not really forward all headers.

**Comment by cshum** [comment]
Thanks for you comment. The original use case of `-http-loader-forward-all-headers` is to clone the browser request header when proxying, so it looks a coming from a browser. 

I do get you point. Can probably rename the `-http-loader-forward-all-headers` option into something more descriptive. 
Forwarding the `Host` header serves a different purpose but will break the existing use case, so it is better to create a separated option if we are trying to bring that in.

**Comment by cshum** [comment]
`-http-loader-forward-all-headers` now renamed to `-http-loader-forward-client-headers`
