### ISSUE TITLE
Memory spike after imagor upgrade

### ISSUE THREAD

**Issue by ipmb** [cshum/imagor#363]
I recently upgraded a production imagor instance from `0.8.11` to `1.4.4`. The service was previously very stable, but now after a few minutes, we see memory spike above the 2GB limit for the container at which point it is killed. We haven't changed any flags with the upgrade. Here's an example of what we're seeing:

![image](https://github.com/cshum/imagor/assets/319156/183ccf88-9e98-4adf-b277-ab4de2e9f3ac)

We're running with the following options:

```
-imagor-unsafe
-port=8888
-server-access-log
-http-loader-insecure-skip-verify-transport
-http-loader-allowed-sources=my-bucket.s3.amazonaws.com
-imagor-process-concurrency=30
```

(it's running behind an Nginx proxy that validating requests which is why we have `-imagor-unsafe`)

**Comment by cshum** [comment]
what about lowering the -imagor-process-concurrency?
Say the number of CPU cores x2

**Comment by ipmb** [comment]
I lowered the concurrency to 2 (running on 1 CPU containers) and bumped the memory from 2GB -> 3GB and am still seeing the issue. It is less frequent than with a concurrency of 30, but still happens far more often than on `0.8.1`.

![image](https://github.com/cshum/imagor/assets/319156/cc0ccdaf-58b4-4539-b18d-bdac4bbdba92)

**Comment by ipmb** [comment]
I tracked these down to a number of different images that are generated with URLs like this:

```
/unsafe/877x20000/smart/filters:strip_exif()/{source_url}
```

On `0.8.11` this image is generated in <50ms. On `1.4.11` it runs until it exhausts the available memory and gets killed >20s on this setup. 

The URLs are getting generated by a different app and I'm guessing the intent there is to allow it to be as wide as possible without exceeding 877px in height. I'm guessing there's a better way to accomplish that, but it also feels like this is undesired behavior by imagor too.

**Comment by ipmb** [comment]
Looks like I can block these with the [image bomb prevention](https://github.com/cshum/imagor#image-bombs-prevention), so I guess this boils down to two questions:

1. Is the performance regression on these expected or a bug?
2. Is there a better way to do a smart resize by height only while maintaining the aspect ratio?

**Comment by cshum** [comment]
@ipmb are you able to test out v0.9.12 as well https://github.com/cshum/imagor/releases/tag/v0.9.12
The biggest changes from v0.9 to v1 is streaming. See if that is the regression.

Streaming increases throughput. Not sure if that also means it is trying to bite off more than it can chew.

**Comment by cshum** [comment]
> Is there a better way to do a smart resize by height only while maintaining the aspect ratio?

or do you mean the `/fit-in/` parameter?

```
localhost:8888/unsafe/fit-in/877x1000/smart/filters:strip_exif()/{IMAGE}
```

**Comment by ipmb** [comment]
Dug into the performance a bit more and why it was fast in previous versions and discovered that `0.8.11` was returning a `406` status code which is probably why it was so fast. `1.4.4` is actually trying to generate the thumbnail.

I'm going to go ahead and close this issue. Thanks for your help @cshum and sorry for the extra noise!
