### ISSUE TITLE
Question: Is there a way to avoid cached image response?

### ISSUE THREAD

**Issue by amit-yp** [cshum/imagor#374]
- we have a use-case where we don't want response from imagor-cached-bucket, for certain image/bucket.
- Q: is there any way to avoid cached image response? or force create cache image in imagor bucket?

**Comment by cshum** [comment]
If caching refers to Result Storage, you may use `preview()` filter:

> preview() skips the result storage even if result storage is enabled. Useful for conditional caching

For caching regarding to response headers, you may try some of the config options:
```
  -imagor-cache-header-ttl duration
        imagor HTTP cache header ttl for successful image response (default 168h0m0s)
  -imagor-cache-header-swr duration
        imagor HTTP Cache-Control header stale-while-revalidate for successful image response (default 24h0m0s)
  -imagor-cache-header-no-cache
        imagor HTTP Cache-Control header no-cache for successful image response
```
