### ISSUE TITLE
Add source whitelist

### ISSUE THREAD

**Issue by estahn** [cshum/imagor#38]
We have a large number of services and sharing the secret between the services has been proven difficult. As an alternative we are using `ALLOWED_SOURCES` in thumbor:

```
ALLOWED_SOURCES: >
            [".*\.foobar\.com","my\.foobar\.com", "sendbird-ap-9\.s3\.amazonaws\.com"]
```

This will only accept and process images from the listed sources.

Looking at something similar in imagor.

**Comment by cshum** [comment]
The equivalent in form of environment variable:
```
HTTP_LOADER_ALLOWED_SOURCES=*.foobar.com,my.foobar.com,sendbird-ap-9.s3.amazonaws.com
```
from the configuration arguments
```
  -http-loader-allowed-sources string
        HTTP Loader allowed hosts whitelist to load images from if set. Accept csv wth glob pattern e.g. *.google.com,*.github.com.
```

**Comment by estahn** [comment]
🤦🏼 Should have put my reading glasses on 🤓 . Thanks!

**Comment by estahn** [comment]
🤦🏼 Should have put my reading glasses on 🤓 . Thanks!
