### ISSUE TITLE
Question: Watermark upscaling

### ISSUE THREAD

**Issue by jvahldick** [cshum/imagor#397]
Hey there,

I noticed that these two lines of the watermark filter have been using SizeDown.
https://github.com/cshum/imagor/blob/v1.4.7/vips/filter.go#L51
https://github.com/cshum/imagor/blob/v1.4.7/vips/filter.go#L57

Is there any specific reason to use it instead SizeBoth?
At least from some tests I've done using SizeBoth, it works well there in case the base image is bigger than the max size of the watermark image.

**Comment by cshum** [comment]
Fixed in v1.4.12
