### ISSUE TITLE
Access rights considerations in a docker installation

### ISSUE THREAD

**Issue by asitemade4u** [cshum/imagor#4]
I have an image present at the right location (I checked), with the right authorizations, with a fairly standard name: `IMG_20180408_153807553_HDR.jpg`

And yet it is not treated by the Imagor server with this error:
`{"Op":"Get","URL":"https://pho/tst/IMG_20180408_153807553_HDR.jpg","Err":{"Op":"dial","Net":"tcp","Source":null,"Addr":null,"Err":{"Err":"no such host","Name":"pho","Server":"127.0.0.11:53","IsTimeout":false,"IsTemporary":false,"IsNotFound":true}}}`

Other images with underscores or uppercase letters are being treated fine in the exact same environment.
The only difference is that the image weighs 3MB but that should not be an issue and is not what the error reports anyway.

Please let me know what I am doing wrong.

**Comment by asitemade4u** [comment]
I rebooted the server and it works fine now.
Sorry.

**Comment by asitemade4u** [comment]
Actually, it is fairly random, because another image is not being treated now. I have a hunch it is because of the image size (the last one is 3.6MB)

**Comment by asitemade4u** [comment]
Here is the screen copy of the `/mnt/data/` folder in the stack:

![image](https://user-images.githubusercontent.com/11460106/145636053-5c4bd34d-e535-4285-9661-1e018df853b3.png)

The image is indeed here and yet I get thie new error message:

```bash
{"Op":"Get","URL":"https://pho/tst/IMG_20180408_152248953_HDR.jpg","Err":{"Op":"dial","Net":"tcp","Source":null,"Addr":null,"Err":{"Err":"no such host","Name":"pho","Server":"127.0.0.11:53","IsTimeout":false,"IsTemporary":false,"IsNotFound":true}}}
```

**Comment by asitemade4u** [comment]
OK, I get it now.
If I change the access rights to `777` (which is insecure) to the images in the folder, they are treated.
Could you add a notice in teh documentation explaining what access rights you expect the image to have?

`-rwxrwxrwx` : good but terribly insecure
`-rw`: not good

**Comment by cshum** [comment]
It is currently requesting 0755 permission for mkdir
and 0666 for create file.

v0.2.4 ddded permission options for file storage mkdir and write, by setting these env variables:
```yaml
      FILE_STORAGE_MKDIR_PERMISSION: 0755
      FILE_STORAGE_WRITE_PERMISSION: 0666
```

https://hub.docker.com/layers/shumc/imagor/0.2.4/images/sha256-2e87998ea5e83eb74720b01decb50b9209dfd37f60a2ef04277ef87556a991de?context=repo

**Comment by asitemade4u** [comment]
Great, that was the rightg thing to do.
