### ISSUE TITLE
Feature Request: Header Auth Support?

### ISSUE THREAD

**Issue by Sugarlessmuffins** [cshum/imagor#427]
Is it possible to add "Authorization" Header on the image?

What i mean is Header for image output from imagor. it to prevent the image getting stealed.

**Comment by cshum** [comment]
Perhaps you can try the `expire(timestamp)` filter, alongside with URL signature?  
https://github.com/cshum/imagor?tab=readme-ov-file#utility-filters
https://github.com/cshum/imagor?tab=readme-ov-file#url-signature

**Comment by AlekseyArh** [comment]
> Is it possible to add "Authorization" Header on the image?
> 
> What i mean is Header for image output from imagor. it to prevent the image getting stealed.

You can use nginx as one of the options.

```nginx
server {

    listen 80;
    listen [::]:80;
    server_name img.example.com;

    location / {
        if ($http_authorization != "Bearer 1234") {
            return 401;
        }
        proxy_pass http://imagor;
    }

}

```


```bash
# curl -I 'http://img.example.com/{...}/test.jpg'
HTTP/1.1 401 Unauthorized
```


```bash
# curl --header "Authorization: Bearer 1234" -I 'http://img.example.com/{...}/test.jpg'
HTTP/1.1 200 OK
```
