### ISSUE TITLE
[Question] Create thumbnail along the longest side

### ISSUE THREAD

**Issue by Shamil-R** [cshum/imagor#461]
I have a large image. I need to create a thumbnail, but I only know the long side.
Example: the maximum side of the thumbnail is 300. The original image is 1000 by 500. Then the thumbnail will be 300 by 150.
I figured out how to make a thumbnail using imagor, but I don't know how to get the metadata of the original image. I read the original image from the stream. Reading the entire image and saving it to a file or to RAM is not optimal, I want to find an optimal solution. Does anyone know how to get image metadata from the stream?

**Comment by cshum** [comment]
Have you tried `/meta`?
https://github.com/cshum/imagor?tab=readme-ov-file#metadata-and-exif

**Comment by Shamil-R** [comment]
I use imagor like lib and i wrote this code: https://gist.github.com/Shamil-R/c61240bcf39d22deb633a01122aa4e0d

But it look like to complicated. How to simplify this solution?

**Comment by cshum** [comment]
There are two things that can be simplified:

By constructing the imagor blob using `stream` as input, there is no need to read the entire bytes to memory.
```go
	in := imagor.NewBlob(func() (reader io.ReadCloser, size int64, err error) {
		return stream, 0, nil
	})
```

> the maximum side of the thumbnail is 300. The original image is 1000 by 500. Then the thumbnail will be 300 by 150.

By using the `FitIn:  true,` option, it does exactly such requirement by setting `Width` and `Height` to be 300 at maximum.
So there is no need to get the original dimension and calculate manually.
```go
	out, err := app.ServeBlob(ctx, in, imagorpath.Params{
		Width:  300,
		Height: 300,
		FitIn:  true,
		Filters: []imagorpath.Filter{
			{"format", base.App.GetConfig().Preview.Image.OutputFormat},
		},
	})
```

**Comment by Shamil-R** [comment]
@cshum 
Thanks a lot
