### ISSUE TITLE
Suppport for transparrent round corners.

### ISSUE THREAD

**Issue by alex-savguira-orioninc** [cshum/imagor#462]
Hello, 

Imagor API follows the Thumbor model which in the latest incarnations seem to support transparent round corners. 

https://thumbor.readthedocs.io/en/latest/round_corners.html

Is it possible to add this functionality to the main code tree?  This is a very useful feature in some cases. 

Thanks a lot in advance, 

Alex.

**Comment by cshum** [comment]
imagor round corners are transparent by default, if output format supports transparency such as png or webp

```
http://localhost:8000/unsafe/filters:round_corner(20):format(png)/https://thumbor.readthedocs.io/en/latest/_images/tom_before_brightness.jpg
```

**Comment by alex-savguira-orioninc** [comment]
Thank you so much. It looks I have stumbled upon firefox problem :) I have actually tried the default round_corner with no parameter, but when I copy/pasted image - found out no transparency. That said when I do save the image or use copy/paste from Chrome, there is no issue. Thanks again for the quick answer.
