### ISSUE TITLE
best way to handle large gifs?

### ISSUE THREAD

**Issue by 0xTanX** [cshum/imagor#48]
anyone have recommendations on how to handle large gifs. I find the processing time slow and i do notice that the resize makes the gifs have empty frames at the end...

**Comment by cshum** [comment]
One way would be to output as WebP format, which is much faster to process and supports both animation and transparency.

This can be done by adding filter `format(webp)` explicitly. Or by enabling `IMAGOR_AUTO_WEBP=1` in server env config to automatically output WebP if browser supports.

**Comment by cshum** [comment]
`shumc/imagor:0.8.20` significantly improved GIF performance by leveraging [cgif](https://github.com/dloebl/cgif) and libvips [gif save](https://www.libvips.org/2021/11/14/What%27s-new-in-8.12.html), with tested 2x faster export speed and 5x less memory usage.
