### ISSUE TITLE
Question about max_bytes

### ISSUE THREAD

**Issue by cocorossello** [cshum/imagor#56]
I was just trying the new max_bytes filter and I found the following that the following URL gives http 406 status
http://localhost:8000/unsafe/fit-in/2000x0/filters:max_bytes(270000):format(webp)/https%3A%2F%2Fstatic.travelconline.com%2Fheaderimages%2FuRzH8mtvVvUQ-zwjpegjpegjpeg.jpeg

I have to use a bigger max_bytes until it fits. then I get a 200 status. I suspect that this filter does not work with jpeg images, is this right?

Thanks!

**Comment by cshum** [comment]
Hi @cocorossello this should be fixed in v0.8.22 :)
```
docker run -p 8000:8000 shumc/imagor:0.8.22 -imagor-unsafe
```

**Comment by cocorossello** [comment]
Awesome.

I confirm it works fine, thanks!
