### ISSUE TITLE
Is there a way to restrict files so that they are an image?

### ISSUE THREAD

**Issue by 0xTanX** [cshum/imagor#64]
I am noticing I can pass google.com as a path to the example and it will show or render google.com. Is there a way to restrict the input so that it only resizes images or certain file types?

**Comment by 0xTanX** [comment]
Actually I do see the 406 error with unsupported format, however on the browser side I will see google.com rendered. Is this because of the http-loader?

**Comment by cshum** [comment]
Imagor v0.9.3 added option to disable error response body:
```
docker run -p 8000:8000 shumc/imagor:0.9.3 -debug -imagor-unsafe -imagor-disable-error-body
```
This URL
```
http://localhost:8000/unsafe/fit-in/2000x0/google.com
```
Would result an empty 406 response

**Comment by 0xTanX** [comment]
thanks !
