### ISSUE TITLE
fill filter compatibility with thumbor?

### ISSUE THREAD

**Issue by gingerlime** [cshum/imagor#7]
Excited to see imagor ! We're pretty heavy users of thumbor, and I also maintain the docker versions of thumbor (+ caching layer) at https://github.com/MinimalCompact/thumbor/

I took imagor for a quick spin as a drop-in replacement, and it seems to work quite well out of the box. One thing I already found however. It seems like the `fill` filter isn't entirely compatible with thumbor?

We have a URL that looks ilke this `/{hash}/fit-in/205x205/filters:fill(FFFFFF,true):format(jpeg)/path/to/image.png`. With thumbor, the background is white, whereas it is black with imagor

Would we need to change the fill params? or are you guys planning on making it compatible with thumbor?

**Comment by cshum** [comment]
Thanks for reporting! Please try docker image `shumc/imagor:0.2.5` which fixes the fill args parsing for this case.

https://hub.docker.com/layers/shumc/imagor/0.2.5/images/sha256-a534cf0119c876db8d65819aa63d0efa8136c227b964aa258afc3e75c8626ff9?context=explore

The current implementation simply handles transparency. 
Implementing fill while neglecting transparency would require additional effort.
I am not sure why anyone would really want that, though.

**Comment by gingerlime** [comment]
Thanks for the speedy reply. It seems to work as expected 👍

**Comment by gingerlime** [comment]
> Just that I am not sure why anyone would really want that, though.

Yes, I can't think of any use-case ... perhaps it was just something that was added later by thumbor, and they kept the old behaviour for backwards-compatibility?
