### ISSUE TITLE
The image on Docker Hub is not multi-arch.

### ISSUE THREAD

**Issue by mrmachine** [cshum/imagor#81]
But the GitHub Actions workflow appears to be attempting to build and push a multi-arch image.

<img width="748" alt="image" src="https://user-images.githubusercontent.com/51939/179880693-aab04acd-77fa-4cfa-86f4-7f68b237b43e.png">

![image](https://user-images.githubusercontent.com/51939/179880773-e2e3fa7d-9b87-4d0e-bf1a-80459f46e2d8.png)

Perhaps the config is building both platforms with the same tag and overwriting the arm64 image with the amd64 image, instead of pushing two separate images with a multi-arch manifest?

**Comment by mrmachine** [comment]
I see now. The GitHub Action is pushing to GHCR, not Docker Hub. But the repo still exists and appears to be up-to-date (even if only amd64) on Docker Hub, and the README links to Docker Hub.

Is GHCR the canonical repository? If so, perhaps update the README and delete the Docker Hub mirror, or reconfigure the mirror to host the multi-arch image.

Cheers.

**Comment by cshum** [comment]
Docker hub will still be updated but README will be based on GHCR

**Comment by mrmachine** [comment]
Will Docker Hub still be amd64 only?

**Comment by cshum** [comment]
Yes. Docker Hub is still updated on new tag, but the legacy build process that pushes to docker hub will not be changed anymore, which is amd64 only.
